// File autogenerated by genseccomp.py - edit at your peril!!

#include <errno.h>
#include <linux/filter.h>

#include "seccomp/seccomp_bpfs.h"
const sock_filter x86_64_app_filter[] = {
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 0, 0, 110),
    BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 202, 108, 0),  // futex
    BPF_JUMP(BPF_JMP | BPF_JEQ | BPF_K, 16, 107, 0),   // ioctl
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 160, 53, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 95, 27, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 38, 13, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 24, 7, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 8, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 5, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 4, 101, 100),  // read|write|open|close
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 6, 100, 99),   // fstat
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 17, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 16, 98,
             97),  // lseek|mmap|mprotect|munmap|brk|rt_sigaction|rt_sigprocmask|rt_sigreturn
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 21, 97, 96),  // pread64|pwrite64|readv|writev
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 35, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 32, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 29, 94, 93),  // sched_yield|mremap|msync|mincore|madvise
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 33, 93, 92),  // dup
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 37, 92, 91),  // nanosleep|getitimer
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 89, 7, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 58, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 44, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 43, 88, 87),  // setitimer|getpid|sendfile|socket|connect
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 57, 87,
        86),  // sendto|recvfrom|sendmsg|recvmsg|shutdown|bind|listen|getsockname|getpeername|socketpair|setsockopt|getsockopt|clone
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 72, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 64, 85, 84),  // vfork|execve|exit|wait4|kill|uname
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 82, 84,
             83),  // fcntl|flock|fsync|fdatasync|truncate|ftruncate|getdents|getcwd|chdir|fchdir
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 93, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 91, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 90, 81, 80),  // readlink
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 92, 80, 79),  // fchmod
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 94, 79, 78),  // fchown
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 124, 13, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 115, 7, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 107, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 104, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 103, 74,
             73),  // umask|gettimeofday|getrlimit|getrusage|sysinfo|times|ptrace|getuid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 105, 73, 72),  // getgid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 112, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 111, 71, 70),  // geteuid|getegid|setpgid|getppid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 113, 70, 69),  // setsid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 120, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 117, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 116, 67, 66),  // getgroups
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 119, 66, 65),  // setresuid|getresuid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 122, 65, 64),  // getresgid|getpgid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 140, 5, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 137, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 135, 1, 0),
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 132, 61,
        60),  // getsid|capget|capset|rt_sigpending|rt_sigtimedwait|rt_sigqueueinfo|rt_sigsuspend|sigaltstack
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 136, 60, 59),  // personality
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 139, 59, 58),  // statfs|fstatfs
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 157, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 155, 1, 0),
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 153, 56,
        55),  // getpriority|setpriority|sched_setparam|sched_getparam|sched_setscheduler|sched_getscheduler|sched_get_priority_max|sched_get_priority_min|sched_rr_get_interval|mlock|munlock|mlockall|munlockall
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 156, 55, 54),  // pivot_root
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 159, 54, 53),  // prctl|arch_prctl
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 262, 27, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 221, 13, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 203, 7, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 179, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 162, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 161, 48, 47),  // setrlimit
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 163, 47, 46),  // sync
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 186, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 180, 45, 44),  // quotactl
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 201, 44,
        43),  // gettid|readahead|setxattr|lsetxattr|fsetxattr|getxattr|lgetxattr|fgetxattr|listxattr|llistxattr|flistxattr|removexattr|lremovexattr|fremovexattr|tkill
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 217, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 206, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 205, 41, 40),  // sched_setaffinity|sched_getaffinity
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 211, 40,
             39),  // io_setup|io_destroy|io_getevents|io_submit|io_cancel
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 220, 39, 38),  // getdents64|set_tid_address|restart_syscall
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 251, 7, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 233, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 228, 1, 0),
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 227, 35,
        34),  // fadvise64|timer_create|timer_settime|timer_gettime|timer_getoverrun|timer_delete
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 232, 34,
             33),  // clock_gettime|clock_getres|clock_nanosleep|exit_group
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 247, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 235, 32, 31),  // epoll_ctl|tgkill
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 248, 31, 30),  // waitid
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 257, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 254, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 253, 28, 27),  // ioprio_set|ioprio_get
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 256, 27, 26),  // inotify_add_watch|inotify_rm_watch
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 261, 26, 25),  // openat|mkdirat|mknodat|fchownat
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 314, 13, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 285, 7, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 280, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 275, 1, 0),
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 273, 21,
        20),  // newfstatat|unlinkat|renameat|linkat|symlinkat|readlinkat|fchmodat|faccessat|pselect6|ppoll|unshare
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 279, 20, 19),  // splice|tee|sync_file_range|vmsplice
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 283, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 282, 18, 17),  // utimensat|epoll_pwait
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 284, 17, 16),  // timerfd_create
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 306, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 302, 1, 0),
    BPF_JUMP(
        BPF_JMP | BPF_JGE | BPF_K, 300, 14,
        13),  // fallocate|timerfd_settime|timerfd_gettime|accept4|signalfd4|eventfd2|epoll_create1|dup3|pipe2|inotify_init1|preadv|pwritev|rt_tgsigqueueinfo|perf_event_open|recvmmsg
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 303, 13, 12),  // prlimit64
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 312, 12,
             11),  // syncfs|sendmmsg|setns|getcpu|process_vm_readv|process_vm_writev
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 332, 5, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 324, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 322, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 320, 8,
             7),  // sched_setattr|sched_getattr|renameat2|seccomp|getrandom|memfd_create
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 323, 7, 6),  // execveat
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 329, 6,
             5),  // membarrier|mlock2|copy_file_range|preadv2|pwritev2
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 440, 3, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 434, 1, 0),
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 333, 3, 2),  // statx
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 435, 2, 1),  // pidfd_open
    BPF_JUMP(BPF_JMP | BPF_JGE | BPF_K, 441, 1, 0),  // process_madvise
    BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_ALLOW),
};

const size_t x86_64_app_filter_size = sizeof(x86_64_app_filter) / sizeof(struct sock_filter);
