LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := static.c
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE := static
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:=\
                timer_deadlock.c 
LOCAL_CFLAGS:= -O2 -std=c99
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE:=timer_deadlock
include $(BUILD_EXECUTABLE)



include $(CLEAR_VARS)
LOCAL_SRC_FILES:=\
                timer_depletion.c 
LOCAL_CFLAGS:= -O2 -std=c99
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE:=timer_depletion
include $(BUILD_EXECUTABLE)



include $(CLEAR_VARS)
LOCAL_SRC_FILES:= timer_depletion2.c 
LOCAL_CFLAGS:= -O2 -std=c99
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE:=timer_depletion2
include $(BUILD_EXECUTABLE)


include $(CLEAR_VARS)
LOCAL_SRC_FILES:= arc4.c 
LOCAL_CFLAGS:= -O2 -std=c99
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE:=arc4
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := t.cpp
LOCAL_MULTILIB := both
LOCAL_MODULE := t
LOCAL_MODULE_STEM_32 := t32
LOCAL_MODULE_STEM_64 := t64
LOCAL_CLANG := false
LOCAL_STRIP_MODULE := false
LOCAL_SDK_VERSION := 23
#LOCAL_FORCE_STATIC_EXECUTABLE := true
include $(BUILD_EXECUTABLE)

