// Autogenerated file - edit at your peril!!

#include <linux/filter.h>
#include <errno.h>

#include "seccomp_bpfs.h"
const sock_filter x86_64_app_filter[] = {
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 0, 0, 98),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 137, 49, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 91, 25, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 35, 13, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 16, 7, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 5, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 3, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 2, 91, 90), //read|write
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 4, 90, 89), //close
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 8, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 6, 88, 87), //fstat
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 15, 87, 86), //lseek|mmap|mprotect|munmap|brk|rt_sigaction|rt_sigprocmask
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 32, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 24, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 21, 84, 83), //ioctl|pread64|pwrite64|readv|writev
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 29, 83, 82), //sched_yield|mremap|msync|mincore|madvise
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 33, 82, 81), //dup
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 58, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 44, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 38, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 37, 78, 77), //nanosleep|getitimer
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 43, 77, 76), //setitimer|getpid|sendfile|socket|connect
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 56, 76, 75), //sendto|recvfrom|sendmsg|recvmsg|shutdown|bind|listen|getsockname|getpeername|socketpair|setsockopt|getsockopt
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 79, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 72, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 64, 73, 72), //vfork|execve|exit|wait4|kill|uname
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 78, 72, 71), //fcntl|flock|fsync|fdatasync|truncate|ftruncate
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 82, 71, 70), //getcwd|chdir|fchdir
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 114, 11, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 104, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 95, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 93, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 92, 66, 65), //fchmod
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 94, 65, 64), //fchown
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 103, 64, 63), //umask|gettimeofday|getrlimit|getrusage|sysinfo|times|ptrace|getuid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 112, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 107, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 105, 61, 60), //getgid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 111, 60, 59), //geteuid|getegid|setpgid|getppid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 113, 59, 58), //setsid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 124, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 120, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 118, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 116, 55, 54), //setregid|getgroups
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 119, 54, 53), //getresuid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 122, 53, 52), //getresgid|getpgid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 135, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 127, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 126, 50, 49), //getsid|capget
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 132, 49, 48), //rt_sigpending|rt_sigtimedwait|rt_sigqueueinfo|rt_sigsuspend|sigaltstack
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 136, 48, 47), //personality
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 247, 23, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 187, 11, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 160, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 157, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 140, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 139, 42, 41), //statfs|fstatfs
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 153, 41, 40), //getpriority|setpriority|sched_setparam|sched_getparam|sched_setscheduler|sched_getscheduler|sched_get_priority_max|sched_get_priority_min|sched_rr_get_interval|mlock|munlock|mlockall|munlockall
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 159, 40, 39), //prctl|arch_prctl
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 179, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 162, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 161, 37, 36), //setrlimit
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 163, 36, 35), //sync
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 180, 35, 34), //quotactl
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 221, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 217, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 203, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 200, 31, 30), //readahead|setxattr|lsetxattr|fsetxattr|getxattr|lgetxattr|fgetxattr|listxattr|llistxattr|flistxattr|removexattr|lremovexattr|fremovexattr
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 205, 30, 29), //sched_setaffinity|sched_getaffinity
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 219, 29, 28), //getdents64|set_tid_address
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 233, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 228, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 227, 26, 25), //fadvise64|timer_create|timer_settime|timer_gettime|timer_getoverrun|timer_delete
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 232, 25, 24), //clock_gettime|clock_getres|clock_nanosleep|exit_group
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 235, 24, 23), //epoll_ctl|tgkill
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 283, 11, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 262, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 257, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 254, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 248, 19, 18), //waitid
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 256, 18, 17), //inotify_add_watch|inotify_rm_watch
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 261, 17, 16), //openat|mkdirat|mknodat|fchownat
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 280, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 275, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 273, 14, 13), //newfstatat|unlinkat|renameat|linkat|symlinkat|readlinkat|fchmodat|faccessat|pselect6|ppoll|unshare
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 279, 13, 12), //splice|tee|sync_file_range|vmsplice
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 282, 12, 11), //utimensat|epoll_pwait
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 302, 5, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 299, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 285, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 284, 8, 7), //timerfd_create
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 297, 7, 6), //fallocate|timerfd_settime|timerfd_gettime|accept4|signalfd4|eventfd2|epoll_create1|dup3|pipe2|inotify_init1|preadv|pwritev
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 300, 6, 5), //recvmmsg
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 318, 3, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 306, 1, 0),
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 303, 3, 2), //prlimit64
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 312, 2, 1), //syncfs|sendmmsg|setns|getcpu|process_vm_readv|process_vm_writev
BPF_JUMP(BPF_JMP|BPF_JGE|BPF_K, 319, 1, 0), //getrandom
BPF_STMT(BPF_RET|BPF_K, SECCOMP_RET_ALLOW),
};

const size_t x86_64_app_filter_size = sizeof(x86_64_app_filter) / sizeof(struct sock_filter);
